### ISSUE TITLE
Next upgrade break the build command 

### ISSUE THREAD

**Issue by nicolas-lescop** [calvinckho/react-capacitor-jitsi-meet-sample#1]
Hello :)

I tried to install the latest version you updated yesterday, but I can't build anymore.

<img width="931" alt="image" src="https://github.com/user-attachments/assets/69d2acfd-bcf1-45fb-b57a-044d3e79c3b7">

Also, the Page.tsx seems to import a new file, but I don't see it anywhere.

![image (6)](https://github.com/user-attachments/assets/33660303-5cc2-4ffc-a812-a5aab587bf98)
![image (7)](https://github.com/user-attachments/assets/9144a201-ae28-49d6-b3a9-329a11c28510)

Thank you for your great work!

**Comment by calvinckho** [comment]
Thanks @nicolas-lescop for catching this. I just added the missed files.

**Comment by calvinckho** [comment]
@nicolas-lescop did you get to pull the missing files and build again?

**Comment by marvynorourkeTT** [comment]
hi @calvinckho ,

I'm encountering an issue when building and running the test application provided to check functionality. Upon launching the application on Android, it crashes immediately, and I receive the following error message:

```{
      "header": {
        "logLevel": "ERROR",
        "pid": 15270,
        "tid": 15270,
        "applicationId": "jitsidemo.restvo.com",
        "processName": "jitsidemo.restvo.com",
        "tag": "JitsiMeetSDK",
        "timestamp": {
          "seconds": 1731492993,
          "nanos": 485000000
        }
      },
      "message": "JitsiMeetUncaughtExceptionHandler FATAL ERROR\njava.lang.RuntimeException: Unable to instantiate activity ComponentInfo{jitsidemo.restvo.com/jitsidemo.restvo.com.MainActivity}: java.lang.ClassNotFoundException: Didn\u0027t find class \"jitsidemo.restvo.com.MainActivity\" on path: DexPathList[[zip file \"/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk\"],nativeLibraryDirectories\u003d[/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/lib/arm64, /data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4047)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)\n\tat android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)\n\tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)\n\tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loopOnce(Looper.java:230)\n\tat android.os.Looper.loop(Looper.java:319)\n\tat android.app.ActivityThread.main(ActivityThread.java:8919)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)\nCaused by: java.lang.ClassNotFoundException: Didn\u0027t find class \"jitsidemo.restvo.com.MainActivity\" on path: DexPathList[[zip file \"/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk\"],nativeLibraryDirectories\u003d[/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/lib/arm64, /data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]\n\tat dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:637)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:573)\n\tat android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)\n\tat androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:44)\n\tat android.app.Instrumentation.newActivity(Instrumentation.java:1378)\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4034)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322) \n\tat android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) \n\tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) \n\tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) \n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) \n\tat android.os.Handler.dispatchMessage(Handler.java:106) \n\tat android.os.Looper.loopOnce(Looper.java:230) \n\tat android.os.Looper.loop(Looper.java:319) \n\tat android.app.ActivityThread.main(ActivityThread.java:8919) \n\tat java.lang.reflect.Method.invoke(Native Method) \n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) \n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) \n\njava.lang.RuntimeException: Unable to instantiate activity ComponentInfo{jitsidemo.restvo.com/jitsidemo.restvo.com.MainActivity}: java.lang.ClassNotFoundException: Didn\u0027t find class \"jitsidemo.restvo.com.MainActivity\" on path: DexPathList[[zip file \"/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk\"],nativeLibraryDirectories\u003d[/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/lib/arm64, /data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4047)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)\n\tat android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)\n\tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)\n\tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loopOnce(Looper.java:230)\n\tat android.os.Looper.loop(Looper.java:319)\n\tat android.app.ActivityThread.main(ActivityThread.java:8919)\n\tat java.lang.reflect.Method.invoke(Native Method)"
    },
    {
      "header": {
        "logLevel": "ERROR",
        "pid": 15270,
        "tid": 15270,
        "applicationId": "jitsidemo.restvo.com",
        "processName": "jitsidemo.restvo.com",
        "tag": "JitsiMeetSDK",
        "timestamp": {
          "seconds": 1731492993,
          "nanos": 485000000
        }
      },
      "message": "\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)\nCaused by: java.lang.ClassNotFoundException: Didn\u0027t find class \"jitsidemo.restvo.com.MainActivity\" on path: DexPathList[[zip file \"/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk\"],nativeLibraryDirectories\u003d[/data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/lib/arm64, /data/app/~~RdE56D1vhHbJ8MmQMyH_VA\u003d\u003d/jitsidemo.restvo.com-7w7YG6PDHUuzAGSdfxfdvQ\u003d\u003d/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]\n\tat dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:637)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:573)\n\tat android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)\n\tat androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:44)\n\tat android.app.Instrumentation.newActivity(Instrumentation.java:1378)\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4034)\n\t... 12 more"
    },
```
    
I’ve been also trying to build the test project on iOS, but I encountered an issue in Xcode:

`[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:
project 'path/to/Project.xcodeproj'`

Unless I’m mistaken, it seems that the .xcodeproj file (or other necessary project files for iOS) may not have been pushed to the repository. Without it, I’m unable to build the project on iOS.

**Comment by nicolas-lescop** [comment]
Hello @calvinckho,

I encounter the same problem as @marvynorourkeTT

**Comment by calvinckho** [comment]
@nicolas-lescop @marvynorourkeTT I apologize for the missed files. I added them to the repo and pushed them (MainActivity.java in Android and .xcodeproj in iOS). I have also tested the repo on a new machine/device and it should be working for you guys as well.

**Comment by nicolas-lescop** [comment]
Hello @calvinckho,

 Now I have this issue when I build the project

<img width="701" alt="image" src="https://github.com/user-attachments/assets/8f666770-61b2-4199-89b6-3ecfe6a27f97">

I've installed `@types/jest`and the build works, but the app still crash when I launch it on android studio.

![image (10)](https://github.com/user-attachments/assets/9e940afc-33c3-4871-b396-d9ba4fb74f40)
![image (9)](https://github.com/user-attachments/assets/82a82e83-b0d3-4f5c-b675-56da2d044f7d)
![image (8)](https://github.com/user-attachments/assets/4e103f18-c1f3-4516-bce8-b7a6cdddf9d1)

**Comment by calvinckho** [comment]
hi @nicolas-lescop, i need to see your full logcat output in order to know the root cause of your problem.

**Comment by marvynorourkeTT** [comment]
Hello,
I wanted to share some observations regarding the issues I’ve encountered:

### On Android

The application builds successfully on Android, which is great.
However, just like in our main application ([Issue#122](https://github.com/calvinckho/capacitor-jitsi-meet/issues/122)), we are not detecting any events from the Jitsi integration.
Here’s the behavior I tested using the provided code:

- Start a video call with another user.
- End the video call.
- At this point, the `onConferenceLeft` event is supposed to be triggered, which should execute a `history.push` to navigate to `/Lobby`.

Unfortunately, what I observe is that there’s no navigation happening on the TypeScript side. The app remains on the same screen, showing the component "behind" the Jitsi video interface.

Could you please check if there might be an issue with the event handling or bridging? Let me know if you need more details or if I should test something else.

### On iOS

When attempting to build the project, I encountered the following error:

```
[fatal] Error: react-capacitor-jitsi-meet-sample/ios/App/App/capacitor.config.json: ENOENT: no such file or directory, open 'react-capacitor-jitsi-meet-sample/ios/App/App/capacitor.config.json'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at readFileSync (/path/to/node_modules/jsonfile/index.js:50:22)
    at writePluginJSON (/path/to/node_modules/@capacitor/cli/dist/util/iosplugin.js:52:49)
    at generateIOSPackageJSON (/path/to/node_modules/@capacitor/cli/dist/util/iosplugin.js:64:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/path/to/react-capacitor-jitsi-meet-sample/ios/App/App/capacitor.config.json'
}
```
It seems like the `capacitor.config.json` file is either missing or not in the expected directory. Could you verify this and let me know how to proceed?

Thank you for your help!

**Comment by calvinckho** [comment]
I added all available window event listeners to VideoContainer.tsx and added console.log to display the data objects. Now when you run in Android Studio, search "Capacitor/Console" in logcat. It should show you all the events that are received in JS.

![Screenshot 2024-11-18 at 2 30 59 PM](https://github.com/user-attachments/assets/c946c99a-92ed-4f15-b91f-2684898ec4f6)

For iOS, I added capacitor.config.json back to the repo. It was included in the gitignore by Capacitor because it was supposed to be generated in each new build.

**Comment by marvynorourkeTT** [comment]
Hello,

I noticed that you’re testing the application on `Android 10`, and I believe this might be the key difference here. Out of curiosity, I tested the application on a Pixel 7 running `Android 10`, and everything worked as expected.

However, the phone I’m using for my tests runs `Android 14`, and that’s where I’m experiencing the issue. On this device, I’m not seeing any logs appear in my Capacitor console. Could it be that there’s an issue with compatibility on newer Android versions?

Regarding iOS, I was able to build the application and successfully detect connection events using both a virtual machine for an iPhone 15 running `iOS 17.4` and a real iPhone 8 device running `iOS 16.7.10`. I didn’t encounter the crash described in the initial issue, which is promising.

Let me know if you need additional details or if I should test something specific.

Thank you!

**Comment by calvinckho** [comment]
Thanks @marvynorourkeTT for working with me to identify this hard-to-find bug that occurs only in newer Android SDKs.

I was able to trace and discover [the broadcast receiver bug](https://github.com/calvinckho/capacitor-jitsi-meet/commit/ff2801b1386b0d30905415d8165d58dd7398ac6d), as you have reported in Android 14. It has been fixed in capacitor-jitsi-meet@6.2.1. 

![Screenshot 2024-11-21 at 1 27 01 AM](https://github.com/user-attachments/assets/f35d7912-3409-48a5-9725-deba04e42efd)

**Comment by calvinckho** [comment]
@marvynorourkeTT @nicolas-lescop any luck with running the newest plugin on the sample project?

**Comment by marvynorourkeTT** [comment]
Hello,

I wanted to let you know that everything is working well with the test project—thank you for providing it! However, we still need to test the iOS part on our main application, as we’re still experiencing crashes when launching the Jitsi SDK.

If needed, we can follow up on the other issue to address this specific problem.

Thank you for your support, and we’ll keep you updated after further testing !
